### ISSUE TITLE
Clarify commit process

### ISSUE THREAD

**Issue by zabbal** [uptane/uptane-test#5]
Something fishy is happening in this repository. The PR https://github.com/uptane/uptane-test/pull/3 was merged yet I do not see it's commits in https://github.com/uptane/uptane-test/commits/master

Is this a github glitch or somebody force-pushed to the repo and re-wrote the git history?

I suggest to avoid pushing anything directly to master branch and only make changes via PRs so we get proper transparency and git history. Also, never ever, under no circumstances force-push to the public repository unless it's a separate personal branch.

**Comment by tkfu** [comment]
Not sure what happened, but I've now turned on branch protection so it doesn't happen again. @zabbal, can you submit a new PR containing the commits that disappeared?

**Comment by zabbal** [comment]
Will do, thanks. To double-check - as of now repository owners still can override this and force-push to master directly?

**Comment by tkfu** [comment]
No, I set it so that the restriction applies to repo administrators as well. So unless github's settings are very misleading, even owners shouldn't be able to.

(Of course, if you have that access and you need to force push, you can disable the restriction. But the idea is just to have a guardrail.)
